name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npx nx run-many --target=lint --all
      - run: npx nx run-many --target=build --all
      - run: npx nx run-many --target=test --all
        env:
          CI: true
